accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
]

app_name = "accounts"

core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

app_name = "core"

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("", include("accounts.urls"))
]

accounts/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        """
        Creates and returns a regular user with an email, first name, last name, and password.
        The username is automatically generated by combining first name and last name.
        """
        if not email:
            raise ValueError('The Email field must be set')
        if not first_name:
            raise ValueError('The First name field must be set')
        if not last_name:
            raise ValueError('The Last name field must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        """
        Creates and returns a superuser with an email, first name, last name, and password.
        The username is automatically generated by combining first name and last name.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **extra_fields)


class User(AbstractUser):
    email = models.EmailField(_("email address"), unique=True, error_messages={"unique": "This email is already registered."})
    first_name = models.CharField(_("first name"), max_length=70)
    last_name = models.CharField(_("last name"), max_length=70)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = UserManager()

    def __str__(self) -> str:
        return self.email
    
    @property
    def username(self):
        return self.get_full_name()

adverts/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=64)


class Advert(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=2)
    rating = models.DecimalField(default=0, max_digits=2, decimal_places=1)
    created_at = models.DateTimeField(auto_now_add=True)

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="adverts")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="adverts")


class Review(models.Model):
    text = models.TextField()
    rating = models.DecimalField(default=0, max_digits=2, decimal_places=1, validators=[MaxValueValidator(5), MinValueValidator(0)])
    created_at = models.DateTimeField(auto_now_add=True)

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE, related_name="reviews")

core/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

import os
from hashlib import sha3_224
from datetime import datetime

def custom_upload_directory(instance, filename):
    # Main directory of the upload (is the name of the parent model class)
    directory = instance.parent_type.model

    # Subdirectory of the upload (is hashed version of the parent's id)
    subderictory_hash = sha3_224()
    subderictory_hash.update(f"{instance.parent_id}".encode())
    subderictory = subderictory_hash.hexdigest()

    # Hashed version of the upload file
    filename, filetype = os.path.splitext(filename)
    filename_hash = sha3_224()
    filename_hash.update(f"{filename}{datetime.now()}".encode()) # add current time to the name of 
    filename = filename_hash.hexdigest()                         # the file and then hash it

    return f"{directory}/{subderictory}/{filename}{filetype}"

# Create your models here.
class UploadFile(models.Model):
    file = models.FileField(upload_to=custom_upload_directory)

    parent_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    parent_id = models.PositiveIntegerField()
    parent = GenericForeignKey("parent_type", "parent_id")

    def __str__(self):
        return self.file.name

accounts/forms.py
from typing import Any
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

class RegistrationForm(UserCreationForm):
    usable_password = None

    class Meta:
        model = get_user_model()
        fields = ["email", "first_name", "last_name", "password1", "password2"]

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

class LoginForm(AuthenticationForm):
    def __init__(self, request: Any = ..., *args: Any, **kwargs: Any) -> None:
        super().__init__(request, *args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import views as auth_views
from accounts.forms import RegistrationForm, LoginForm

# Create your views here.
class RegisterView(CreateView):
    form_class = RegistrationForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("accounts:login")

class LoginView(auth_views.LoginView):
    template_name = "accounts/login.html"
    form_class = LoginForm

adverts/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = "core/home.html"
    

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="d-flex justify-content-center">
        <form action="{% url 'accounts:login' %}" method="post" class="form-control w-50 rounded-0 py-3">
            <h2 class="text-center">Вхід</h2>

            {% csrf_token %}
            {{form.as_p}}
            
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary" style="width: 90%">Ввійти</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="d-flex justify-content-center">
        <form action="{% url 'accounts:register' %}" method="post" class="form-control w-50 rounded-0 py-3 px-4">
            {% csrf_token %}

            <h2 class="text-center mb-0">Реєстрація</h2>

            <div class="my-4">
                {{form.as_p}}
            </div>
            
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary" style="width: 95%">Зареєструватися</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marketplace</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <!-- Static files (css, js) -->
    {% load static %}
</head>
<body class="bg-light">
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}

    <!-- Bootstrap JS -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="text-center">
        <h1>Home page</h1>
        <p>Welcome to the home page!</p>
    </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar bg-dark" data-bs-theme="dark">
    <div class="container">
        <!-- Home link -->
        <a href="{% url 'core:home' %}" class="navbar-brand mb-0 fs-2 fw-bold h1">Marketplace</a>

        <!-- Auth links -->
        <div class="btn-group">
            <a href="{% url 'accounts:login' %}" class="btn btn-secondary">Вхід</a>
            <div class="vr" style="width: 2px; color: white; opacity: 1;"></div>
            <a href="{% url 'accounts:register' %}" class="btn btn-secondary">Реєстрація</a>
        </div>
    </div>
</nav>